workflows:
  debug-apk:
    name: Debug APK Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_CHANNEL: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - abdulbakiturkmenoglu@gmail.com
