workflows:
  build-xbot:
    name: Build X Bot APK
    environment:
      flutter: "3.19.5"
      android: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
