name: x_bot
description: Binance API ile otomatik kripto al-sat botu
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^2.3.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
